# First two arguments are passed to benchmark program.
# For example, ./bench.script --quick
./benchmark --memcpy abc --test 0 $1 $2
./benchmark --memcpy abc --test 1 $1 $2
./benchmark --memcpy abc --test 48 $1 $2
./benchmark --memcpy abcde --test 43 $1 $2
./benchmark --memcpy abc --test 2 $1 $2
./benchmark --memset abcde --test 0 $1 $2
./benchmark --memset abcde --test 1 $1 $2
./benchmark --memset abcde --test 4 $1 $2
./benchmark --memset abcde --test 2 $1 $2
